/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    java
    `maven-publish`
    kotlin("jvm") version "1.5.21"
    id("org.jetbrains.kotlin.plugin.serialization") version "1.5.21"
    id("com.github.ben-manes.versions") version "0.39.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "dev.chieppa"
version = "2.0-SNAPSHOT"
description = "unofficial_ao3_wrapper"
java.sourceCompatibility = JavaVersion.VERSION_11

application {
    mainClass.set("dev.chieppa.AO3WrapperKt")
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.0")
    implementation("org.jsoup:jsoup:1.13.1")
    implementation("io.github.microutils:kotlin-logging-jvm:2.0.11")
    implementation("org.slf4j:slf4j-api:1.7.31")
    implementation("org.slf4j:slf4j-simple:1.7.31")
    testImplementation("org.assertj:assertj-core:3.11.1")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.5.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    testImplementation("io.kotest:kotest-runner-junit5-jvm:4.5.0")
    testImplementation("io.kotest:kotest-assertions-core-jvm:4.5.0")
}

val KtorVersion: String = "1.6.4"

dependencies {
    implementation("io.ktor:ktor-client-core:$KtorVersion")
    implementation("io.ktor:ktor-client-cio:$KtorVersion")
    implementation("io.ktor:ktor-client-logging:$KtorVersion")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
