package constants.work_properties

enum class Language(val search_param: String, val language: String) {

    SO("so", "af Soomaali"),
    AFR("afr", "Afrikaans"),
    AR("ar", "العربية"),
    ARC("arc", "ܐܪܡܝܐ | ארמיא"),
    HY("hy", "հայերեն"),
    ID("id", "Bahasa Indonesia"),
    MS("ms", "Bahasa Malaysia"),
    BG("bg", "Български"),
    BN("bn", "বাংলা"),
    JV("jv", "Basa Jawa"),
    BE("be", "беларуская"),
    BOS("bos", "Bosanski"),
    BR("br", "brezhoneg"),
    CA("ca", "Català"),
    CS("cs", "Čeština"),
    CHN("chn", "Chinuk Wawa"),
    CY("cy", "Cymraeg"),
    DA("da", "Dansk"),
    DE("de", "Deutsch"),
    ET("et", "eesti keel"),
    EL("el", "Ελληνικά"),
    EN("en", "English"),
    ES("es", "Español"),
    EO("eo", "Esperanto"),
    EU("eu", "Euskara"),
    FA("fa", "فارسی"),
    FIL("fil", "Filipino"),
    FR("fr", "Français"),
    FUR("fur", "Furlan"),
    GA("ga", "Gaeilge"),
    GD("gd", "Gàidhlig"),
    GL("gl", "Galego"),
    GOT("got", "𐌲𐌿𐍄𐌹𐍃𐌺𐌰"),
    HAK("hak", "中文-客家话"),
    KO("ko", "한국어"),
    HAU("hau", "Hausa | هَرْشَن هَوْسَ"),
    HI("hi", "हिन्दी"),
    HR("hr", "Hrvatski"),
    IA("ia", "Interlingua"),
    ZU("zu", "isiZulu"),
    IS("is", "Íslenska"),
    IT("it", "Italiano"),
    HE("he", "עברית"),
    KAT("kat", "ქართული"),
    QKZ("qkz", "Khuzdul"),
    KIR("kir", "Кыргызча"),
    SW("sw", "Kiswahili"),
    HT("ht", "kreyòl ayisyen"),
    FCS("fcs", "Langue des signes québécoise"),
    LV("lv", "Latviešu valoda"),
    LB("lb", "Lëtzebuergesch"),
    LT("lt", "Lietuvių kalba"),
    LA("la", "Lingua latina"),
    HU("hu", "Magyar"),
    MK("mk", "македонски"),
    ML("ml", "മലയാളം"),
    MNC("mnc", "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ"),
    MR("mr", "मराठी"),
    MON("mon", "ᠮᠣᠩᠭᠣᠯ ᠪᠢᠴᠢᠭ᠌ | Монгол Кирилл үсэг"),
    MY("my", "မြန်မာဘာသာ"),
    NAN("nan", "中文-闽南话 臺語"),
    NL("nl", "Nederlands"),
    JA("ja", "日本語"),
    NO("no", "Norsk"),
    PS("ps", "پښتو"),
    NDS("nds", "Plattdüütsch"),
    PL("pl", "Polski"),
    PTBR("ptBR", "Português brasileiro"),
    PTPT("ptPT", "Português europeu"),
    PA("pa", "ਪੰਜਾਬੀ"),
    QYA("qya", "Quenya"),
    RO("ro", "Română"),
    RU("ru", "Русский"),
    SCO("sco", "Scots"),
    SQ("sq", "Shqip"),
    SJN("sjn", "Sindarin"),
    SI("si", "සිංහල"),
    SK("sk", "Slovenčina"),
    SLV("slv", "Slovenščina"),
    GEM("gem", "Sprēkō Þiudiskō"),
    SR("sr", "српски"),
    FI("fi", "Suomi"),
    SV("sv", "Svenska"),
    TA("ta", "தமிழ்"),
    TH("th", "ไทย"),
    TQX("tqx", "Thermian"),
    BOD("bod", "བོད་སྐད་"),
    VI("vi", "Tiếng Việt"),
    TLH("tlh", "tlhIngan-Hol"),
    QTP("qtp", "Toki Pona"),
    TR("tr", "Türkçe"),
    UK("uk", "Українська"),
    UIG("uig", "ئۇيغۇر تىلى"),
    WUU("wuu", "中文-吴语"),
    YI("yi", "יידיש"),
    YUE("yue", "中文-广东话 粵語"),
    ZH("zh", "中文-普通话 國語"),
    UNKNOWN("", "Unknown") // fallback
    ;

    companion object {
        val languageMap: Map<String, Language>

        init {
            languageMap = HashMap()
            for (language in values()) {
                languageMap[language.language] = language
            }
        }
    }
}